D:\>ssh -L 8888:localhost:8888 root@8.141.7.139
root@8.141.7.139's password:
Welcome to Ubuntu 24.04.2 LTS (GNU/Linux 6.8.0-63-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/pro

 System information as of Wed Aug 13 07:34:58 PM CST 2025

  System load:  0.0                Processes:             134
  Usage of /:   31.0% of 98.05GB   Users logged in:       1
  Memory usage: 55%                IPv4 address for eth0: 172.21.141.42
  Swap usage:   0%

 * Strictly confined Kubernetes makes edge and IoT secure. Learn how MicroK8s
   just raised the bar for easy, resilient and secure K8s cluster deployment.

   https://ubuntu.com/engage/secure-kubernetes-at-the-edge

Expanded Security Maintenance for Applications is not enabled.

30 updates can be applied immediately.
To see these additional updates run: apt list --upgradable

20 additional security updates can be applied with ESM Apps.
Learn more about enabling ESM Apps service at https://ubuntu.com/esm


1 updates could not be installed automatically. For more details,
see /var/log/unattended-upgrades/unattended-upgrades.log

*** System restart required ***

Welcome to Alibaba Cloud Elastic Compute Service !

Last login: Wed Aug 13 16:32:43 2025 from 119.1.87.211
conda: command not found
😼 已开启代理环境
(base) root@iZ2ze539tadlwtl57jxfh1Z:~#   cd /root/Code/Voice_DH_live
(base) root@iZ2ze539tadlwtl57jxfh1Z:~/Code/Voice_DH_live# conda activate dh_live
(dh_live) root@iZ2ze539tadlwtl57jxfh1Z:~/Code/Voice_DH_live# python web_demo/server_realtime.py
LLM配置: 提供商=doubao, 模型=doubao-seed-1.6-250615
INFO:     Started server process [177392]
INFO:     Waiting for application startup.
ASR模型正在初始化，请稍等
asr: engine loaded in 7.64s
TTS模型正在初始化，请稍等
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8888 (Press CTRL+C to quit)
INFO:     127.0.0.1:36478 - "POST /eb_stream HTTP/1.1" 200 OK
gen_stream 1.0 1
----- streaming request -----
get_audio:  你好！很高兴见到你呀～我是人工智能助手，
run_tts 你好！很高兴见到你呀～我是人工智能助手， 1.0 1
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '～'
get_audio:  你可以叫我豆包。不管是想聊天、
run_tts 你可以叫我豆包。不管是想聊天、 1.0 1
get_audio:  问问题，还是需要帮忙做点什么，
run_tts 问问题，还是需要帮忙做点什么， 1.0 1
get_audio:  都可以跟我说哦～
run_tts 都可以跟我说哦～ 1.0 1
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '～'
INFO:     204.76.203.193:48212 - "GET http%3A//ip-api.com/json/ HTTP/1.1" 404 Not Found
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
INFO:     127.0.0.1:33872 - "POST /eb_stream HTTP/1.1" 200 OK
gen_stream 1.0 1
----- streaming request -----
get_audio:  256×10=2560

**答案**：
run_tts 256×10=2560

**答案**： 1.0 1
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '256'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '×'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '10'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '='
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '2560'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '
'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '
'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '*'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '*'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '*'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '*'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '：'
get_audio:  2560
run_tts 2560 1.0 1
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '2560'
/project/sherpa-onnx/csrc/offline-tts-vits-impl.h:Generate:214 Failed to convert 2560 to token IDs
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/_utils.py", line 77, in collapse_excgroups
  |     yield
  |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/responses.py", line 271, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 772, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    |     return await self.app(scope, receive, send)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    |     raise exc
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/routing.py", line 716, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/routing.py", line 736, in app
    |     await route.handle(scope, receive, send)
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/routing.py", line 290, in handle
    |     await self.app(scope, receive, send)
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/routing.py", line 78, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    |     await response(scope, receive, send)
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/responses.py", line 270, in __call__
    |     with collapse_excgroups():
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/contextlib.py", line 158, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/_utils.py", line 83, in collapse_excgroups
    |     raise exc
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/responses.py", line 274, in wrap
    |     await func()
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/responses.py", line 254, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "/root/Code/Voice_DH_live/web_demo/server_realtime.py", line 109, in gen_stream
    |     base64_string = await get_audio(llm_answer_cache, voice_id=voice_id, voice_speed=voice_speed)
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/Code/Voice_DH_live/web_demo/voiceapi/tts.py", line 140, in get_audio
    |     soundfile.write(
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/soundfile.py", line 363, in write
    |     with SoundFile(file, 'w', samplerate, channels,
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/soundfile.py", line 690, in __init__
    |     self._file = self._open(file, mode_int, closefd)
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/soundfile.py", line 1265, in _open
    |     raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
    | soundfile.LibsndfileError: Error opening <_io.BytesIO object at 0x7645541eae30>: Internal error : SF_INFO struct incomplete.
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/routing.py", line 78, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await response(scope, receive, send)
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/responses.py", line 270, in __call__
    with collapse_excgroups():
  File "/root/anaconda3/envs/dh_live/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/_utils.py", line 83, in collapse_excgroups
    raise exc
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/responses.py", line 274, in wrap
    await func()
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/responses.py", line 254, in stream_response
    async for chunk in self.body_iterator:
  File "/root/Code/Voice_DH_live/web_demo/server_realtime.py", line 109, in gen_stream
    base64_string = await get_audio(llm_answer_cache, voice_id=voice_id, voice_speed=voice_speed)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/Code/Voice_DH_live/web_demo/voiceapi/tts.py", line 140, in get_audio
    soundfile.write(
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/soundfile.py", line 363, in write
    with SoundFile(file, 'w', samplerate, channels,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/soundfile.py", line 690, in __init__
    self._file = self._open(file, mode_int, closefd)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/soundfile.py", line 1265, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening <_io.BytesIO object at 0x7645541eae30>: Internal error : SF_INFO struct incomplete.
INFO:     127.0.0.1:47652 - "POST /eb_stream HTTP/1.1" 200 OK
gen_stream 1.0 1
----- streaming request -----
get_audio:  广州和上海作为中国超大城市，
run_tts 广州和上海作为中国超大城市， 1.0 1
get_audio:  地铁网络均承担着巨大的通勤压力，
run_tts 地铁网络均承担着巨大的通勤压力， 1.0 1
get_audio:  **“上海地铁不拥挤”
run_tts **“上海地铁不拥挤” 1.0 1
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '*'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '*'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '“'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '”'
get_audio:  的说法与实际情况存在偏差**——上海地铁在早晚高峰时段，
run_tts 的说法与实际情况存在偏差**——上海地铁在早晚高峰时段， 1.0 1
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '*'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '*'
get_audio:  多条核心线路（如1号线、
run_tts 多条核心线路（如1号线、 1.0 1
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '（'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '1'
get_audio:  2号线、9号线、11号线等）
run_tts 2号线、9号线、11号线等） 1.0 1
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '2'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '9'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '11'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '）'
get_audio:  同样面临严重拥挤，
run_tts 同样面临严重拥挤， 1.0 1
get_audio:  部分站点的客流强度甚至位居全国前列。
run_tts 部分站点的客流强度甚至位居全国前列。 1.0 1
get_audio:  两地地铁的拥挤程度更多是“
run_tts 两地地铁的拥挤程度更多是“ 1.0 1
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '“'
get_audio:  线路差异”“时段差异”
run_tts 线路差异”“时段差异” 1.0 1
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '”'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '”'
get_audio:  ，而非“整体差异”
run_tts ，而非“整体差异” 1.0 1
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '“'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '”'
get_audio:  。以下从客观角度分析两地地铁拥挤的共性原因及部分差异化特征，
run_tts 。以下从客观角度分析两地地铁拥挤的共性原因及部分差异化特征， 1.0 1
get_audio:  帮助更全面理解这一现象：
run_tts 帮助更全面理解这一现象： 1.0 1
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '：'
get_audio:


### 一、
run_tts


### 一、 1.0 1
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '
'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '
'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '
'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '#'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '#'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '#'
get_audio:  先澄清：上海地铁同样面临拥挤挑战
上海地铁是全球运营里程最长（
run_tts 先澄清：上海地铁同样面临拥挤挑战
上海地铁是全球运营里程最长（ 1.0 1
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '：'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '
'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '（'
get_audio:  截至2023年超800公里）
run_tts 截至2023年超800公里） 1.0 1
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '2023'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '800'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '）'
get_audio:  、日均客流量最大（
run_tts 、日均客流量最大（ 1.0 1
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '（'
get_audio:  工作日超1000万人次）
run_tts 工作日超1000万人次） 1.0 1
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '1000'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '）'
get_audio:  的地铁网络之一。根据上海申通地铁公开数据，
run_tts 的地铁网络之一。根据上海申通地铁公开数据， 1.0 1
get_audio:  2023年早高峰（
run_tts 2023年早高峰（ 1.0 1
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '2023'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '（'
get_audio:  7:30-9:00）
run_tts 7:30-9:00） 1.0 1
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '7'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV ':'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '30'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '-'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '9'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV ':'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '00'
/project/sherpa-onnx/csrc/jieba-lexicon.cc:ConvertTextToTokenIds:169 Ignore OOV '）'
/project/sherpa-onnx/csrc/offline-tts-vits-impl.h:Generate:214 Failed to convert 7:30-9:00） to token IDs
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/_utils.py", line 77, in collapse_excgroups
  |     yield
  |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/responses.py", line 271, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 772, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    |     return await self.app(scope, receive, send)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    |     raise exc
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/routing.py", line 716, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/routing.py", line 736, in app
    |     await route.handle(scope, receive, send)
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/routing.py", line 290, in handle
    |     await self.app(scope, receive, send)
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/routing.py", line 78, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    |     await response(scope, receive, send)
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/responses.py", line 270, in __call__
    |     with collapse_excgroups():
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/contextlib.py", line 158, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/_utils.py", line 83, in collapse_excgroups
    |     raise exc
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/responses.py", line 274, in wrap
    |     await func()
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/responses.py", line 254, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "/root/Code/Voice_DH_live/web_demo/server_realtime.py", line 96, in gen_stream
    |     base64_string = await get_audio(first_sentence, voice_id=voice_id, voice_speed=voice_speed)
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/Code/Voice_DH_live/web_demo/voiceapi/tts.py", line 140, in get_audio
    |     soundfile.write(
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/soundfile.py", line 363, in write
    |     with SoundFile(file, 'w', samplerate, channels,
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/soundfile.py", line 690, in __init__
    |     self._file = self._open(file, mode_int, closefd)
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/soundfile.py", line 1265, in _open
    |     raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
    | soundfile.LibsndfileError: Error opening <_io.BytesIO object at 0x764550b0acf0>: Internal error : SF_INFO struct incomplete.
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/routing.py", line 78, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await response(scope, receive, send)
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/responses.py", line 270, in __call__
    with collapse_excgroups():
  File "/root/anaconda3/envs/dh_live/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/_utils.py", line 83, in collapse_excgroups
    raise exc
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/responses.py", line 274, in wrap
    await func()
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/starlette/responses.py", line 254, in stream_response
    async for chunk in self.body_iterator:
  File "/root/Code/Voice_DH_live/web_demo/server_realtime.py", line 96, in gen_stream
    base64_string = await get_audio(first_sentence, voice_id=voice_id, voice_speed=voice_speed)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/Code/Voice_DH_live/web_demo/voiceapi/tts.py", line 140, in get_audio
    soundfile.write(
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/soundfile.py", line 363, in write
    with SoundFile(file, 'w', samplerate, channels,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/soundfile.py", line 690, in __init__
    self._file = self._open(file, mode_int, closefd)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/dh_live/lib/python3.11/site-packages/soundfile.py", line 1265, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening <_io.BytesIO object at 0x764550b0acf0>: Internal error : SF_INFO struct incomplete.